import { Github } from 'lucide-react'

import { Button } from '@/components/ui/button'
import { Separator } from '@/components/ui/separator'
import { Textarea } from '@/components/ui/textarea'

export default function Home() {
  return (
    <div className="flex min-h-screen flex-col">
      <div className="flex items-center justify-between border-b px-6 py-3">
        <h1 className="text-xl font-bold">
          upload<span className="text-red-600">.ai</span>
        </h1>
        <div className="flex items-center gap-3">
          <span className="text-sm text-muted-foreground">
            Developed by Fillipe Romero
          </span>

          <Separator orientation="vertical" className="h-6" />

          <Button variant="outline">
            <Github className="mr-2 h-4 w-4" />
            Github
          </Button>
        </div>
      </div>

      <main className="flex flex-1 gap-6 p-6">
        <div className="flex flex-1 flex-col gap-4">
          <div className="grid flex-1 grid-rows-2 gap-4">
            <Textarea
              className="resize-none p-4 leading-relaxed"
              placeholder="Include the prompt for the AI"
            />
            <Textarea
              className="resize-none p-4 leading-relaxed"
              placeholder="Result generated by the AI"
              readOnly
            />
          </div>

          <p className="text-sm text-muted-foreground">
            Remember: You can use the variable{' '}
            <code className="text-violet-400">{'{transcription}'}</code> in your
            prompt to add the transcription of the selected video
          </p>
        </div>

        <aside className="w-80"></aside>
      </main>
    </div>
  )
}
